### ISSUE TITLE
bibtex checker

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/CDL-bibliography#5]
It'd be nice to have a TravisCI or other similar CI check to verify:
- All entries have required fields (e.g. use https://github.com/Pezmc/BibLatex-Check or similar)
- All citation keys follow the required format
- Maybe online verification of references, e.g. using https://pypi.org/project/scholarly/

**Comment by KirstensGitHub** [comment]
If we write something that does all of that, couldn't we write something to just make the citation keys for us? (That is, it sounds like we're essentially writing our own reference management tool for the lab, since existing reference managers don't use our formatting.)

**Comment by KirstensGitHub** [comment]
Or maybe we could write something that takes the bibtex automatically outputted for every paper by google scholar and just changes it to our lab's preferred format?

**Comment by jeremymanning** [comment]
This looks useful: https://github.com/pezmc/biblatex-check

**Comment by jeremymanning** [comment]
Started [this notebook](https://colab.research.google.com/drive/19bcCJnaM7QaxI040cmkAb_NxTRM_mlgG?usp=sharing) to start playing around with some parsing code (uses [scholarly](https://github.com/scholarly-python-package/scholarly))
